apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html-configmap
  namespace: eks-my-app-ns
data:
  index.html: |
    <html>
    <h1> Welcome </h1>
    </br>
    <h1> Demo webserver on EKS </h1>
    </html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
  namespace: eks-my-app-ns
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-app
  namespace: eks-my-app-ns
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: my-app
  strategy: 
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template: 
    metadata: 
      labels: 
        app: my-app
    spec:
      containers: 
        - 
          image: "nicolasmarcoux/my-app:latest"
          env:
            - name: secret
              value: "-----BEGIN CERTIFICATE----------END CERTIFICATE-----"
          imagePullPolicy: Always
          name: my-app
          ports: 
            - 
              containerPort: 80
              name: http
            - 
              containerPort: 443
              name: https
          securityContext:
            readOnlyRootFilesystem: false
          volumeMounts: 
            - 
              mountPath: /etc/nginx/ssl
              name: secret-volume
            - 
              mountPath: /etc/nginx/conf.d
              name: configmap-volume
           # - 
              #mountPath: /usr/share/nginx/html/
              #name: nginx-index-file
              #readOnly: false
      imagePullSecrets: 
        - 
          name: myregistrykey4
      volumes: 
        - 
          name: secret-volume
          secret: 
            #secretName: $(secret)
            secretName: nginx-certs-keys 
        - 
          configMap: 
            name: nginxconfigmap
          name: configmap-volume
        #- 
        #  configMap: 
        #    name: index-html-configmap
        #    defaultMode: 0777
        #  name: nginx-index-file
