---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-ubuntu
  name: my-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ubuntu
  template:
    metadata:
      labels:
        app: my-ubuntu
    spec:
      imagePullSecrets:
        - name: myregistrykey2
      containers:
        - image: nicolasmarcoux/my-ubuntu:latest
          imagePullPolicy: Always
          name: my-ubuntu
