---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu
  name: ubuntu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      imagePullSecrets:
        - name: myregistrykey
      containers:
        -
          command:
            - /bin/bash
            - "-c"
            - "while true; do sleep 1000; done"
          image: "https://hub.docker.com/nicolasmarcoux/my-ubuntu/ubuntu:latest"
          imagePullPolicy: Always
          name: my-ubuntu
