---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-ubuntu
  name: my-ubuntu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-ubuntu
  template:
    metadata:
      labels:
        app: my-ubuntu
    spec:
      containers:
        -
          command:
            - /bin/bash
            - "-c"
            - "while true; do sleep 1000; done"
          image: nicolasmarcoux/my-ubuntu:latest
          imagePullPolicy: Always
          name: my-ubuntu
       imagePullSecrets:
        - name: myregistrykey4     
